export enum ValidationErrorType {
  PARSING_ERROR = "PARSING_ERROR",
  SEMANTIC_ERROR = "SEMANTIC_ERROR",
  CONTEXT_ERROR = "CONTEXT_ERROR",
  PROOF_VERIFICATION_ERROR = "PROOF_VERIFICATION_ERROR",
  INVALID_DOMAIN_ERROR = "INVALID_DOMAIN_ERROR",
  INVALID_CHALLENGE_ERROR = "INVALID_CHALLENGE_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
