export enum ValidationErrorType {
  INVALID_INPUT_ERROR = "INVALID_INPUT_ERROR",
  PARSING_ERROR = "PARSING_ERROR",
  SEMANTIC_ERROR = "SEMANTIC_ERROR",
  CONTEXT_ERROR = "CONTEXT_ERROR",
  PROOF_VERIFICATION_ERROR = "PROOF_VERIFICATION_ERROR",
  INVALID_DOMAIN_ERROR = "INVALID_DOMAIN_ERROR",
  INVALID_CHALLENGE_ERROR = "INVALID_CHALLENGE_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  VERIFIABLE_CREDENTIAL_CREATION_ERROR = "VERIFIABLE_CREDENTIAL_CREATION_ERROR",
  VERIFIABLE_PRESENTATION_CREATION_ERROR = "VERIFIABLE_PRESENTATION_CREATION_ERROR",
}
